language: objective-c

# before_install:
#   - brew update
#   - brew install xctool

notifications:
  email: false

script: xctool ONLY_ACTIVE_ARCH=NO -project Demo/KoaPullToRefresh.xcodeproj -sdk iphonesimulator -scheme KoaPullToRefresh build